import { Inter } from "next/font/google";
import "@/app/_styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    template: "%s - Create Next App",
    default: "Create Next App",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header></header>
        <div>{children}</div>
      </body>
    </html>
  );
}
